### ISSUE TITLE
Usage: GetItemQualityColor(index)

### ISSUE THREAD

**Issue by Quartzfire** [GoldpawsStuff/Bagnon_ItemInfo#12]
Hi,

Updated to latest version earlier today, and now get following LUA:

I see PetTracker is also mentioned, so not sure if it's this addon or the other. PetTracker I updated 10 days ago (3rd Dec) and seemingly had no issues.

23x Bagnon_ItemInfo\main.lua:286: Usage: GetItemQualityColor(index)
[string "=[C]"]: ?
[string "@Bagnon_ItemInfo\main.lua"]:286: in function <Bagnon_ItemInfo\main.lua:257>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `Update'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:128: in function <...faceBagnon\common\Wildpants\classes\item.lua:123>
[string "=[C]"]: in function `Show'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:42: in function <...faceBagnon\common\Wildpants\classes\item.lua:34>
[string "=(tail call)"]: ?
[string "@Bagnon\common\Wildpants\classes\itemGroup.lua"]:124: in function `func'
[string "@PetTracker\libs\MutexDelay-1.0\MutexDelay-1.0-2.lua"]:36: in function <...ns\PetTracker\libs\MutexDelay-1.0\MutexDelay-1.0.lua:30>

Locals:
(*temporary) = nil

**Comment by goldpaw** [comment]
No, it has nothing to do with PetTracker. It's a bug reported by a shared library probably used by multiple addons. It's only mentioning PetTracker because right now that's where the shared library was loaded from. But the bug is definitely in this plugin! 

I updated it to work with classic era and bcc yesterday, and updated all its code to be in line with the latest versions of the separate minor single feature plugins I have. I can sort of see where I might have made a blunder. And probably didn't catch it in my tests because quite frankly I never have enough interesting stuff in my bags. I can almost guess what I need to do to fix it too just by looking at the report and my code. I would however like to be able to reproduce it myself, so I can make sure I get it fixed! 

Did this happen just by logging in and opening the bags, or is it connected to hovering over specific items? Like caged battle pets?

**Comment by goldpaw** [comment]
Actually I don't think I even need to reproduce it. My plugin is checking for rarity color before ever verifying that we have a rarity to begin with. This is a rookie mistake here! :D

I'm on it!

**Comment by goldpaw** [comment]
Hopefully fixed in 1.0.23-Release, which is in queue awaiting approval on curseforge as I'm writing this.

**Comment by Quartzfire** [comment]
Thanks very much for your quick response and action.

I don't have anything exciting in my bags on this character either - was just when logging in that it popped up. Think it also happened when I opened my bags the first time, but not subsequently.

Saying that I have a number of other chars I can test with if you need me to check anything and provide feedback.

**Comment by Quartzfire** [comment]
Still not showing up on curseforge.
I will update as soon as I see it on there and provide feedback.

**Comment by goldpaw** [comment]
It's been live on the webpage for hours, but the app can sometimes be quite slow on fetching the latest versions. They throttle it to avoid every curse client out there constantly downloading full app databases from the server, so it just takes longer there.

**Comment by Quartzfire** [comment]
Managed to download the update a few minutes ago. All looks to now be working as expected. Logged 5 different alts with various gear in bags  and happy to report that no errors were reported back :-) 

Thanks once again for your quick help to get it sorted out.

**Comment by goldpaw** [comment]
Wohoo, awesome! Closing this issue, then, and thanks for testing it out for me! :)
