### ISSUE TITLE
Strange grey out effect of bag items about to mail

### ISSUE THREAD

**Issue by LudiusMaximus** [GoldpawsStuff/Bagnon_ItemInfo#9]
- Start writing a mail.
- Attach an item from your bag to the mail (right click or drag)
- The item gets slightly greyed out as it should.
- Now drag another item from the same bag as the attached item to another location in your bag.
- The attached item gets another even darker greyed out effect. (Should not happen!)
- Some effect remains even after you take the attached item back into your bag. (Should also not happen!)

https://youtu.be/17rTwDgzjjo

Thanks!

**Comment by goldpaw** [comment]
Fixed in latest update.

**Comment by LudiusMaximus** [comment]
Sorry, but I can still reproduce this with your newest version (1.0.15-Release).

**Comment by LudiusMaximus** [comment]
Should I submit a new issue or will you re-open this one? ;-)

**Comment by LudiusMaximus** [comment]
Cool, thanks!
